[package]
name = "descrive-csv"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tabled = "0"
arrow = {version="20", features = ["csv", "prettyprint"]}
clap = {version = "3", features = ["derive"]}